<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodPlanner.Core\FoodPlanner.Core.csproj" />
    <ProjectReference Include="..\FoodPlanner.Services\FoodPlanner.Services.csproj" />
    <ProjectReference Include="..\FoodPlanner.Data\FoodPlanner.Data.csproj" />
  </ItemGroup>

</Project>
