using FoodPlanner.Core.Enums;

namespace FoodPlanner.Core.Services;

public static class ProductCategoryDetector
{
    private static readonly List<(string Keyword, ProductCategory Category)> Rules =
    [
        // Сладости
        ("сгущен", ProductCategory.Sweets),
        ("шоколад", ProductCategory.Sweets),
        ("конфет", ProductCategory.Sweets),
        ("карамель", ProductCategory.Sweets),
        ("зефир", ProductCategory.Sweets),
        ("пастил", ProductCategory.Sweets),
        ("халв", ProductCategory.Sweets),
        ("ирис", ProductCategory.Sweets),
        ("драже", ProductCategory.Sweets),
        ("батончик", ProductCategory.Sweets),
        ("вафл", ProductCategory.Sweets),
        ("морожен", ProductCategory.Sweets),
        ("джем", ProductCategory.Sweets),
        ("варень", ProductCategory.Sweets),
        ("повидл", ProductCategory.Sweets),
        ("мёд", ProductCategory.Sweets),
        ("мед", ProductCategory.Sweets),
        ("сахар", ProductCategory.Sweets),
        ("нутелл", ProductCategory.Sweets),
        ("жевательн", ProductCategory.Sweets),

        // Молочные
        ("сливочн", ProductCategory.Dairy),
        ("сливк", ProductCategory.Dairy),
        ("молок", ProductCategory.Dairy),
        ("кефир", ProductCategory.Dairy),
        ("йогурт", ProductCategory.Dairy),
        ("сметан", ProductCategory.Dairy),
        ("творог", ProductCategory.Dairy),
        ("сыр", ProductCategory.Dairy),
        ("простокваш", ProductCategory.Dairy),
        ("ряженк", ProductCategory.Dairy),
        ("мацони", ProductCategory.Dairy),

        // Масла и жиры
        ("оливков", ProductCategory.OilsAndFats),
        ("подсолнечн", ProductCategory.OilsAndFats),
        ("растительн", ProductCategory.OilsAndFats),
        ("масло", ProductCategory.OilsAndFats),
        ("маргарин", ProductCategory.OilsAndFats),
        ("спред", ProductCategory.OilsAndFats),
        ("майонез", ProductCategory.OilsAndFats),

        // Соусы и специи-префиксы
        ("соус", ProductCategory.Spices),
        ("кетчуп", ProductCategory.Spices),
        ("уксус", ProductCategory.Spices),

        // Консервы и заготовки
        ("консерв", ProductCategory.Canned),
        ("шпрот", ProductCategory.Canned),
        ("тушенк", ProductCategory.Canned),
        ("паштет", ProductCategory.Canned),
        ("икра", ProductCategory.Canned),
        ("закатк", ProductCategory.Canned),
        ("маринован", ProductCategory.Canned),
        ("квашен", ProductCategory.Canned),
        ("солён", ProductCategory.Canned),
        ("солен", ProductCategory.Canned),
        ("оливк", ProductCategory.Canned),
        ("маслин", ProductCategory.Canned),
        ("каперс", ProductCategory.Canned),
        ("корнишон", ProductCategory.Canned),

        // Морепродукты (морская капуста и пр.)
        ("морска", ProductCategory.Seafood),
        ("водоросл", ProductCategory.Seafood),

        // Напитки
        ("кофе", ProductCategory.Beverages),
        ("чай", ProductCategory.Beverages),
        ("какао", ProductCategory.Beverages),
        ("каркад", ProductCategory.Beverages),
        ("сок", ProductCategory.Beverages),
        ("компот", ProductCategory.Beverages),
        ("морс", ProductCategory.Beverages),
        ("квас", ProductCategory.Beverages),
        ("лимонад", ProductCategory.Beverages),
        ("газировк", ProductCategory.Beverages),
        ("минеральн", ProductCategory.Beverages),
        ("пив", ProductCategory.Beverages),
        ("вино", ProductCategory.Beverages),
        ("шампанск", ProductCategory.Beverages),
        ("коньяк", ProductCategory.Beverages),
        ("водка", ProductCategory.Beverages),
        ("энергетик", ProductCategory.Beverages),
        ("вода", ProductCategory.Beverages),

        // Фрукты и ягоды
        ("яблок", ProductCategory.Fruits),
        ("груш", ProductCategory.Fruits),
        ("банан", ProductCategory.Fruits),
        ("апельсин", ProductCategory.Fruits),
        ("мандарин", ProductCategory.Fruits),
        ("лимон", ProductCategory.Fruits),
        ("лайм", ProductCategory.Fruits),
        ("грейпфрут", ProductCategory.Fruits),
        ("помело", ProductCategory.Fruits),
        ("виноград", ProductCategory.Fruits),
        ("персик", ProductCategory.Fruits),
        ("абрикос", ProductCategory.Fruits),
        ("слив", ProductCategory.Fruits),
        ("алыч", ProductCategory.Fruits),
        ("вишн", ProductCategory.Fruits),
        ("черешн", ProductCategory.Fruits),
        ("клубник", ProductCategory.Fruits),
        ("земляник", ProductCategory.Fruits),
        ("малин", ProductCategory.Fruits),
        ("ежевик", ProductCategory.Fruits),
        ("черник", ProductCategory.Fruits),
        ("голубик", ProductCategory.Fruits),
        ("смородин", ProductCategory.Fruits),
        ("крыжовник", ProductCategory.Fruits),
        ("брусник", ProductCategory.Fruits),
        ("клюкв", ProductCategory.Fruits),
        ("дын", ProductCategory.Fruits),
        ("арбуз", ProductCategory.Fruits),
        ("гранат", ProductCategory.Fruits),
        ("хурм", ProductCategory.Fruits),
        ("киви", ProductCategory.Fruits),
        ("манго", ProductCategory.Fruits),
        ("ананас", ProductCategory.Fruits),
        ("авокадо", ProductCategory.Fruits),
        ("фрукт", ProductCategory.Fruits),
        ("цитрус", ProductCategory.Fruits),
        ("ягод", ProductCategory.Fruits),

        // Замороженные продукты
        ("заморож", ProductCategory.Frozen),
        ("пельмен", ProductCategory.Frozen),
        ("вареник", ProductCategory.Frozen),
        ("хинкал", ProductCategory.Frozen),
        ("мант", ProductCategory.Frozen),
        ("голубц", ProductCategory.Frozen),
        ("полуфабрик", ProductCategory.Frozen),
        ("палочк", ProductCategory.Frozen),

        // Крупы и макароны
        ("круп", ProductCategory.Grains),
        ("гречк", ProductCategory.Grains),
        ("овсян", ProductCategory.Grains),
        ("геркулес", ProductCategory.Grains),
        ("рис", ProductCategory.Grains),
        ("пшен", ProductCategory.Grains),
        ("манк", ProductCategory.Grains),
        ("булгур", ProductCategory.Grains),
        ("кускус", ProductCategory.Grains),
        ("перловк", ProductCategory.Grains),
        ("ячмен", ProductCategory.Grains),
        ("макарон", ProductCategory.Grains),
        ("спагет", ProductCategory.Grains),
        ("вермишел", ProductCategory.Grains),
        ("лапш", ProductCategory.Grains),
        ("хлопья", ProductCategory.Grains),
        ("кукуруз", ProductCategory.Grains),
        ("мюсл", ProductCategory.Grains),

        // Хлеб и выпечка
        ("хлеб", ProductCategory.Bakery),
        ("булк", ProductCategory.Bakery),
        ("батон", ProductCategory.Bakery),
        ("багет", ProductCategory.Bakery),
        ("лаваш", ProductCategory.Bakery),
        ("лепешк", ProductCategory.Bakery),
        ("пшеничн", ProductCategory.Bakery),
        ("ржан", ProductCategory.Bakery),
        ("сухар", ProductCategory.Bakery),
        ("крекер", ProductCategory.Bakery),
        ("печенье", ProductCategory.Bakery),
        ("пряник", ProductCategory.Bakery),
        ("кекс", ProductCategory.Bakery),
        ("торт", ProductCategory.Bakery),
        ("пирожн", ProductCategory.Bakery),
        ("пирог", ProductCategory.Bakery),
        ("булочк", ProductCategory.Bakery),
        ("ватрушк", ProductCategory.Bakery),
        ("мука", ProductCategory.Bakery),
        ("тест", ProductCategory.Bakery),
        ("желат", ProductCategory.Bakery),
        ("крахмал", ProductCategory.Bakery),
        ("блин", ProductCategory.Bakery),
        ("олад", ProductCategory.Bakery),
        ("пончик", ProductCategory.Bakery),
        ("сушк", ProductCategory.Bakery),
        ("баранк", ProductCategory.Bakery),
        ("хлебц", ProductCategory.Bakery),

        // Бобовые
        ("бобов", ProductCategory.Legumes),
        ("фасол", ProductCategory.Legumes),
        ("чечевиц", ProductCategory.Legumes),
        ("нут", ProductCategory.Legumes),
        ("соев", ProductCategory.Legumes),
        ("соя", ProductCategory.Legumes),
        ("маш", ProductCategory.Legumes),
        ("горох", ProductCategory.Legumes),

        // Мясо
        ("мяс", ProductCategory.Meat),
        ("говядин", ProductCategory.Meat),
        ("свинин", ProductCategory.Meat),
        ("баранин", ProductCategory.Meat),
        ("телятин", ProductCategory.Meat),
        ("колбас", ProductCategory.Meat),
        ("сосиск", ProductCategory.Meat),
        ("сардельк", ProductCategory.Meat),
        ("фарш", ProductCategory.Meat),
        ("котлет", ProductCategory.Meat),
        ("ветчин", ProductCategory.Meat),
        ("шпик", ProductCategory.Meat),
        ("сало", ProductCategory.Meat),
        ("солонин", ProductCategory.Meat),
        ("гуляш", ProductCategory.Meat),
        ("шашлык", ProductCategory.Meat),
        ("буженин", ProductCategory.Meat),
        ("окорок", ProductCategory.Meat),
        ("бекон", ProductCategory.Meat),
        ("стейк", ProductCategory.Meat),
        ("отбивн", ProductCategory.Meat),
        ("печен", ProductCategory.Meat),
        ("печёнк", ProductCategory.Meat),

        // Птица
        ("куриц", ProductCategory.Poultry),
        ("индейк", ProductCategory.Poultry),
        ("цыплен", ProductCategory.Poultry),
        ("цыплят", ProductCategory.Poultry),
        ("перепел", ProductCategory.Poultry),
        ("утк", ProductCategory.Poultry),
        ("гус", ProductCategory.Poultry),
        ("цесарк", ProductCategory.Poultry),

        // Яйца
        ("перепелин", ProductCategory.Eggs),
        ("яйц", ProductCategory.Eggs),
        ("яичн", ProductCategory.Eggs),

        // Рыба
        ("рыб", ProductCategory.Fish),
        ("семг", ProductCategory.Fish),
        ("лосос", ProductCategory.Fish),
        ("форел", ProductCategory.Fish),
        ("сельд", ProductCategory.Fish),
        ("скумбри", ProductCategory.Fish),
        ("треск", ProductCategory.Fish),
        ("минтай", ProductCategory.Fish),
        ("хек", ProductCategory.Fish),
        ("судак", ProductCategory.Fish),
        ("окун", ProductCategory.Fish),
        ("карп", ProductCategory.Fish),
        ("щук", ProductCategory.Fish),
        ("лещ", ProductCategory.Fish),
        ("камбал", ProductCategory.Fish),
        ("палтус", ProductCategory.Fish),
        ("тунец", ProductCategory.Fish),
        ("сардин", ProductCategory.Fish),
        ("кильк", ProductCategory.Fish),
        ("карась", ProductCategory.Fish),
        ("горбуш", ProductCategory.Fish),
        ("нерк", ProductCategory.Fish),
        ("муксун", ProductCategory.Fish),

        // Морепродукты
        ("креветк", ProductCategory.Seafood),
        ("кальмар", ProductCategory.Seafood),
        ("миди", ProductCategory.Seafood),
        ("осьминог", ProductCategory.Seafood),
        ("краб", ProductCategory.Seafood),
        ("лангуст", ProductCategory.Seafood),
        ("устриц", ProductCategory.Seafood),

        // Специи и приправы
        ("специ", ProductCategory.Spices),
        ("приправ", ProductCategory.Spices),
        ("перец", ProductCategory.Spices),
        ("паприк", ProductCategory.Spices),
        ("карри", ProductCategory.Spices),
        ("куркум", ProductCategory.Spices),
        ("тмин", ProductCategory.Spices),
        ("имбир", ProductCategory.Spices),
        ("лавров", ProductCategory.Spices),
        ("горчиц", ProductCategory.Spices),
        ("хрен", ProductCategory.Spices),
        ("сод", ProductCategory.Spices),
        ("соль", ProductCategory.Spices),
        ("розмарин", ProductCategory.Spices),
        ("зира", ProductCategory.Spices),
        ("аджик", ProductCategory.Spices),
        ("прованск", ProductCategory.Spices),
        ("трав", ProductCategory.Spices),
        ("кориандр", ProductCategory.Spices),
        ("гвоздик", ProductCategory.Spices),
        ("кориц", ProductCategory.Spices),
        ("ванил", ProductCategory.Spices),
        ("мускат", ProductCategory.Spices),
        ("душист", ProductCategory.Spices),
        ("шафран", ProductCategory.Spices),
        ("разрыхлител", ProductCategory.Spices),
        ("дрожжи", ProductCategory.Spices),

        // Орехи и семена
        ("орех", ProductCategory.NutsAndSeeds),
        ("грецк", ProductCategory.NutsAndSeeds),
        ("арахис", ProductCategory.NutsAndSeeds),
        ("миндаль", ProductCategory.NutsAndSeeds),
        ("фундук", ProductCategory.NutsAndSeeds),
        ("кешью", ProductCategory.NutsAndSeeds),
        ("фисташк", ProductCategory.NutsAndSeeds),
        ("семечк", ProductCategory.NutsAndSeeds),
        ("семя", ProductCategory.NutsAndSeeds),
        ("семен", ProductCategory.NutsAndSeeds),
        ("кунжут", ProductCategory.NutsAndSeeds),
        ("льн", ProductCategory.NutsAndSeeds),

        // Овощи
        ("стручков", ProductCategory.Vegetables),
        ("болгарск", ProductCategory.Vegetables),
        ("винегрет", ProductCategory.Vegetables),
        ("овощ", ProductCategory.Vegetables),
        ("горош", ProductCategory.Vegetables),
        ("картоф", ProductCategory.Vegetables),
        ("морков", ProductCategory.Vegetables),
        ("свекл", ProductCategory.Vegetables),
        ("редис", ProductCategory.Vegetables),
        ("редьк", ProductCategory.Vegetables),
        ("реп", ProductCategory.Vegetables),
        ("брюкв", ProductCategory.Vegetables),
        ("капуст", ProductCategory.Vegetables),
        ("броккол", ProductCategory.Vegetables),
        ("цветн", ProductCategory.Vegetables),
        ("помидор", ProductCategory.Vegetables),
        ("томат", ProductCategory.Vegetables),
        ("огурец", ProductCategory.Vegetables),
        ("огурц", ProductCategory.Vegetables),
        ("кабачк", ProductCategory.Vegetables),
        ("баклажан", ProductCategory.Vegetables),
        ("тыкв", ProductCategory.Vegetables),
        ("патиссон", ProductCategory.Vegetables),
        ("лук", ProductCategory.Vegetables),
        ("чеснок", ProductCategory.Vegetables),
        ("сельдерей", ProductCategory.Vegetables),
        ("спарж", ProductCategory.Vegetables),
        ("щавел", ProductCategory.Vegetables),
        ("гриб", ProductCategory.Vegetables),
        ("початк", ProductCategory.Vegetables),

        // Зелень и салаты
        ("шпинат", ProductCategory.Greens),
        ("салат", ProductCategory.Greens),
        ("руккол", ProductCategory.Greens),
        ("зелень", ProductCategory.Greens),
        ("укроп", ProductCategory.Greens),
        ("петрушк", ProductCategory.Greens),
        ("кинз", ProductCategory.Greens),
        ("базилик", ProductCategory.Greens),
        ("мят", ProductCategory.Greens),
    ];

    public static ProductCategory Detect(string name)
    {
        foreach (var (keyword, category) in Rules)
        {
            if (name.Contains(keyword, StringComparison.OrdinalIgnoreCase))
                return category;
        }

        return ProductCategory.Other;
    }
}